// 2025 會考單字片語書 - Vocabulary & Phrase Data
// Grades: 1=Always(≥31x) 2=Usually(21-30x) 3=Often(11-20x) 4=Sometimes(6-10x) 5=Occasionally(1-5x)

const VOCAB_DATA = {
  vocab: [
    {"word":"about","phonetic":"[E'bAUt]","pos":["prep"],"zh":"大約；關於","grade":1},
    {"word":"also","phonetic":"['clso]","pos":["adv"],"zh":"也","grade":1},
    {"word":"as","phonetic":"[Zz]","pos":["prep", "conj"],"zh":"以……的身份；作為；依照；當……時","grade":1},
    {"word":"ask","phonetic":"[Zsk]","pos":["v"],"zh":"問","grade":1},
    {"word":"become","phonetic":"[bI'kVm]","pos":["v"],"zh":"變成","grade":1},
    {"word":"because","phonetic":"[bI'kAs]","pos":["conj"],"zh":"因為","grade":1},
    {"word":"city","phonetic":"['sIti]","pos":["n"],"zh":"都市","grade":1},
    {"word":"different","phonetic":"['dIfRnt]","pos":["adj"],"zh":"不同的","grade":1},
    {"word":"each","phonetic":"[itS]","pos":["adj", "pron"],"zh":"每個；各個","grade":1},
    {"word":"enjoy","phonetic":"[In'dDcI]","pos":["v"],"zh":"喜歡；享受","grade":1},
    {"word":"even","phonetic":"[ivn]","pos":["adj", "adv"],"zh":"均勻的；偶數的；平手的；即使","grade":1},
    {"word":"famous","phonetic":"['feImEs]","pos":["adj"],"zh":"著名的","grade":1},
    {"word":"forget","phonetic":"[fR'get]","pos":["v"],"zh":"忘記","grade":1},
    {"word":"idea","phonetic":"[AI'diE]","pos":["n"],"zh":"主意","grade":1},
    {"word":"if","phonetic":"[If]","pos":["conj"],"zh":"如果","grade":1},
    {"word":"important","phonetic":"[Im'pcrtnt]","pos":["adj"],"zh":"重要的","grade":1},
    {"word":"into","phonetic":"['Intu]","pos":["prep"],"zh":"進入","grade":1},
    {"word":"just","phonetic":"[dDVst]","pos":["adv"],"zh":"正好；剛才","grade":1},
    {"word":"last","phonetic":"[lZst]","pos":["adj", "v", "adv"],"zh":"最後的；持續；最後地","grade":1},
    {"word":"late","phonetic":"[leIt]","pos":["adj"],"zh":"晚的；遲的","grade":1},
    {"word":"learn","phonetic":"[l2n]","pos":["v"],"zh":"學習","grade":1},
    {"word":"life","phonetic":"[lAIf]","pos":["n"],"zh":"人生；生命","grade":1},
    {"word":"live","phonetic":"[lIv]","pos":["v"],"zh":"居住","grade":1},
    {"word":"may","phonetic":"[meI]","pos":["aux"],"zh":"可能","grade":1},
    {"word":"most","phonetic":"[most]","pos":["pron"],"zh":"大部分","grade":1},
    {"word":"place","phonetic":"[pleIs]","pos":["n"],"zh":"地方","grade":1},
    {"word":"please","phonetic":"[pliz]","pos":["adv", "v"],"zh":"請；取悅","grade":1},
    {"word":"problem","phonetic":"['prablEm]","pos":["n"],"zh":"問題","grade":1},
    {"word":"remember","phonetic":"[rI'membR]","pos":["v"],"zh":"記得","grade":1},
    {"word":"should","phonetic":"[SUd]","pos":["aux"],"zh":"將；萬一；竟然；該","grade":1},
    {"word":"since","phonetic":"[sIns]","pos":["prep", "conj"],"zh":"自從……之後；由於；自……以來；因為","grade":1},
    {"word":"stay","phonetic":"[steI]","pos":["v"],"zh":"停留","grade":1},
    {"word":"still","phonetic":"[stIl]","pos":["adj", "adv"],"zh":"靜止的；仍然","grade":1},
    {"word":"than","phonetic":"[TZn]","pos":["prep", "conj"],"zh":"比；超過；比較","grade":1},
    {"word":"then","phonetic":"[Ten]","pos":["adv"],"zh":"當時；之後；那麼","grade":1},
    {"word":"thought","phonetic":"[Oat]","pos":["n"],"zh":"思想","grade":1},
    {"word":"town","phonetic":"[tAUn]","pos":["n"],"zh":"城市","grade":1},
    {"word":"trip","phonetic":"[trIp]","pos":["n"],"zh":"旅行","grade":1},
    {"word":"visit","phonetic":"[vIzIt]","pos":["v", "n"],"zh":"訪問","grade":1},
    {"word":"afraid","phonetic":"[E'freId]","pos":["adj"],"zh":"害怕","grade":2},
    {"word":"already","phonetic":"[al'r3di]","pos":["adv"],"zh":"已經","grade":2},
    {"word":"another","phonetic":"[E'nVTR]","pos":["adj", "pron"],"zh":"另一個","grade":2},
    {"word":"anything","phonetic":"['eniOIG]","pos":["pron"],"zh":"任何事物","grade":2},
    {"word":"around","phonetic":"[E'raUnd]","pos":["prep"],"zh":"差不多；環繞","grade":2},
    {"word":"believe","phonetic":"[bI'liv]","pos":["v"],"zh":"相信","grade":2},
    {"word":"bring","phonetic":"[brIG]","pos":["v"],"zh":"帶來","grade":2},
    {"word":"care","phonetic":"[ker]","pos":["v"],"zh":"關心；照顧","grade":2},
    {"word":"change","phonetic":"[tSeIndD]","pos":["v", "n"],"zh":"改變；更改；零錢","grade":2},
    {"word":"country","phonetic":"[kVntri]","pos":["n"],"zh":"國家；鄉下","grade":2},
    {"word":"decide","phonetic":"[dI'sAId]","pos":["v"],"zh":"決定","grade":2},
    {"word":"during","phonetic":"['dUr.IG]","pos":["prep"],"zh":"在……期間","grade":2},
    {"word":"early","phonetic":"['2.li]","pos":["adj", "adv"],"zh":"早的；提早的；早；提早","grade":2},
    {"word":"English","phonetic":"['IG.glIS]","pos":["n"],"zh":"英語","grade":2},
    {"word":"enough","phonetic":"[E'nVf]","pos":["adj"],"zh":"足夠的","grade":2},
    {"word":"everyone","phonetic":"['ev.ri.wVn]","pos":["pron"],"zh":"每個人","grade":2},
    {"word":"example","phonetic":"[Ig'zZmpL]","pos":["n"],"zh":"例子","grade":2},
    {"word":"favorite","phonetic":"['feI.vr.Et]","pos":["adj"],"zh":"最喜愛的","grade":2},
    {"word":"fact","phonetic":"[fZkt]","pos":["n"],"zh":"事實","grade":2},
    {"word":"grow","phonetic":"[groU]","pos":["v"],"zh":"種植；成長","grade":2},
    {"word":"happen","phonetic":"['hZpn]","pos":["v"],"zh":"發生","grade":2},
    {"word":"hate","phonetic":"['heIt]","pos":["v"],"zh":"憎恨","grade":2},
    {"word":"heavy","phonetic":"['hevi]","pos":["adj"],"zh":"重的","grade":2},
    {"word":"history","phonetic":"['hIstRi]","pos":["n"],"zh":"歷史","grade":2},
    {"word":"hurt","phonetic":"[h2t]","pos":["v"],"zh":"傷害；使疼痛","grade":2},
    {"word":"language","phonetic":"['lZG.gwIdD]","pos":["n"],"zh":"語言","grade":2},
    {"word":"left","phonetic":"[left]","pos":["adj"],"zh":"左邊的","grade":2},
    {"word":"letter","phonetic":"['letR]","pos":["n"],"zh":"信；字母","grade":2},
    {"word":"mean","phonetic":"[min]","pos":["adj", "v"],"zh":"兇的；吝嗇的；意指","grade":2},
    {"word":"meaning","phonetic":"['mi.nIG]","pos":["n"],"zh":"意義","grade":2},
    {"word":"P.M.","phonetic":"[pi.'em]","pos":["abbr"],"zh":"下午","grade":2},
    {"word":"person","phonetic":"['p2.sn]","pos":["n"],"zh":"人","grade":2},
    {"word":"plan","phonetic":"[plZn]","pos":["v", "n"],"zh":"計劃；計畫","grade":2},
    {"word":"popular","phonetic":"['pa.pjE.lR]","pos":["adj"],"zh":"流行的；受歡迎的","grade":2},
    {"word":"price","phonetic":"[prAIs]","pos":["n"],"zh":"價錢","grade":2},
    {"word":"quiet","phonetic":"['kwAI.Et]","pos":["adj"],"zh":"安靜的","grade":2},
    {"word":"road","phonetic":"[roUd]","pos":["n"],"zh":"道路","grade":2},
    {"word":"same","phonetic":"[seIm]","pos":["adj"],"zh":"相同的","grade":2},
    {"word":"serious","phonetic":"['sIr.i.Es]","pos":["adj"],"zh":"嚴肅的；嚴重的；認真的","grade":2},
    {"word":"several","phonetic":"['sev.R.l]","pos":["adj"],"zh":"幾個的","grade":2},
    {"word":"share","phonetic":"[Ser]","pos":["v"],"zh":"分享","grade":2},
    {"word":"something","phonetic":"['sVm.OIG]","pos":["pron"],"zh":"某事","grade":2},
    {"word":"spend","phonetic":"[spend]","pos":["v"],"zh":"花費（錢或時間）","grade":2},
    {"word":"story","phonetic":"['stcr.i]","pos":["n"],"zh":"故事；樓層","grade":2},
    {"word":"surprised","phonetic":"[sR'prAIzd]","pos":["adj"],"zh":"驚訝的","grade":2},
    {"word":"theater","phonetic":"['Oi.E.tR]","pos":["n"],"zh":"戲院；劇院","grade":2},
    {"word":"turn","phonetic":"[t2n]","pos":["v", "n"],"zh":"轉；輪到","grade":2},
    {"word":"use","phonetic":"[juz]","pos":["v", "n"],"zh":"利用；用途","grade":2},
    {"word":"usual","phonetic":"['ju.Du.El]","pos":["adj"],"zh":"例常的","grade":2},
    {"word":"vacation","phonetic":"[veI'keI.SN]","pos":["n"],"zh":"假期","grade":2},
    {"word":"without","phonetic":"[wI'TAUt]","pos":["prep"],"zh":"沒有","grade":2},
    {"word":"wonderful","phonetic":"['wVn.dR.fl]","pos":["adj"],"zh":"很棒的；奇妙的","grade":2},
    {"word":"A.M.","phonetic":"[Zm]","pos":["abbr"],"zh":"上午","grade":3},
    {"word":"able","phonetic":"['eIbL]","pos":["adj"],"zh":"能；有能力的","grade":3},
    {"word":"age","phonetic":"[eIdD]","pos":["n"],"zh":"年齡","grade":3},
    {"word":"almost","phonetic":"['al.moUst]","pos":["adv"],"zh":"幾乎","grade":3},
    {"word":"along","phonetic":"[E'laG]","pos":["prep"],"zh":"沿著","grade":3},
    {"word":"American","phonetic":"[E'mer.I.ken]","pos":["adj", "n"],"zh":"美國的；美洲的；美國人","grade":3},
    {"word":"arrive","phonetic":"[E'rAIv]","pos":["v"],"zh":"到達","grade":3},
    {"word":"art","phonetic":"[art]","pos":["n"],"zh":"藝術","grade":3},
    {"word":"beginning","phonetic":"[bI'gIn.IG]","pos":["n"],"zh":"開始","grade":3},
    {"word":"below","phonetic":"[bI'loU]","pos":["prep"],"zh":"在……之下","grade":3},
    {"word":"between","phonetic":"[bI'twin]","pos":["prep"],"zh":"在……和……之間","grade":3},
    {"word":"bill","phonetic":"[bIl]","pos":["v", "n"],"zh":"記入帳；帳單；鈔票","grade":3},
    {"word":"block","phonetic":"[blak]","pos":["v", "n"],"zh":"阻塞；街區","grade":3},
    {"word":"bore","phonetic":"[bcr]","pos":["v"],"zh":"使厭煩","grade":3},
    {"word":"born","phonetic":"[bcrn]","pos":["adj"],"zh":"出生的；誕生的","grade":3},
    {"word":"bright","phonetic":"[brAIt]","pos":["adj"],"zh":"光亮的","grade":3},
    {"word":"build","phonetic":"[bIld]","pos":["v"],"zh":"建造；蓋","grade":3},
    {"word":"building","phonetic":"['bIl.dIG]","pos":["n"],"zh":"建築物","grade":3},
    {"word":"business","phonetic":"['bIz.nIs]","pos":["n"],"zh":"商業；事","grade":3},
    {"word":"catch","phonetic":"[kZtS]","pos":["v"],"zh":"接（球）；捕獲","grade":3},
    {"word":"celebrate","phonetic":"['sel.E.breIt]","pos":["v"],"zh":"慶祝","grade":3},
    {"word":"center","phonetic":"['sen.tR]","pos":["n"],"zh":"中心（點）","grade":3},
    {"word":"chance","phonetic":"[tSZns]","pos":["n"],"zh":"機會","grade":3},
    {"word":"check","phonetic":"[tSek]","pos":["v", "n"],"zh":"檢查；支票；買單","grade":3},
    {"word":"Chinese","phonetic":"[tSAI'niz]","pos":["adj", "n"],"zh":"中國（人）的；中文；中國人","grade":3},
    {"word":"church","phonetic":"[tS2tS]","pos":["n"],"zh":"教堂","grade":3},
    {"word":"collect","phonetic":"[kE'lekt]","pos":["v"],"zh":"收集","grade":3},
    {"word":"comfortable","phonetic":"['kVmfRtEbL]","pos":["adj"],"zh":"舒適的","grade":3},
    {"word":"convenient","phonetic":"[kEn'vi.niEnt]","pos":["adj"],"zh":"方便的","grade":3},
    {"word":"couldn't","phonetic":"['kUd.nt]","pos":["contraction"],"zh":"不能","grade":3},
    {"word":"course","phonetic":"[kcrs]","pos":["n"],"zh":"課程；科目","grade":3},
    {"word":"dangerous","phonetic":"['deIn.dDR.Es]","pos":["adj"],"zh":"危險的","grade":3},
    {"word":"die","phonetic":"[dAI]","pos":["v", "n"],"zh":"死；骰子","grade":3},
    {"word":"difficult","phonetic":"['dIf.E.kElt]","pos":["adj"],"zh":"困難的","grade":3},
    {"word":"draw","phonetic":"[dra]","pos":["v", "n"],"zh":"畫；繪製；描寫；平局；平手","grade":3},
    {"word":"ever","phonetic":"['evR]","pos":["adv"],"zh":"從來；曾經","grade":3},
    {"word":"excited","phonetic":"[Ik'sAI.tId]","pos":["adj"],"zh":"感到興奮的","grade":3},
    {"word":"exciting","phonetic":"[Ik'sAI.tIG]","pos":["adj"],"zh":"令人興奮的","grade":3},
    {"word":"excuse","phonetic":"[Ik'skjuz]","pos":["v", "n"],"zh":"原諒；借光；藉口","grade":3},
    {"word":"exercise","phonetic":"['ek.sR.sAIz]","pos":["n"],"zh":"運動；習題","grade":3},
    {"word":"experience","phonetic":"[Ik'spIr.i.Ens]","pos":["v", "n"],"zh":"經歷；感受；經驗","grade":3},
    {"word":"fall","phonetic":"[fcl]","pos":["v", "n"],"zh":"掉下；秋天","grade":3},
    {"word":"fan","phonetic":"[fZn]","pos":["n"],"zh":"風扇；扇子；迷友","grade":3},
    {"word":"few","phonetic":"[fju]","pos":["adj", "pron"],"zh":"少數的；一些；一些","grade":3},
    {"word":"final","phonetic":"['fAI.nL]","pos":["adj"],"zh":"最後的","grade":3},
    {"word":"finish","phonetic":"['fIn.IS]","pos":["v"],"zh":"完成","grade":3},
    {"word":"follow","phonetic":"['fa.loU]","pos":["v"],"zh":"遵循；跟隨","grade":3},
    {"word":"foreign","phonetic":"['fcr.En]","pos":["adj"],"zh":"外國的；外來的","grade":3},
    {"word":"fresh","phonetic":"[freS]","pos":["adj"],"zh":"新鮮的","grade":3},
    {"word":"friendly","phonetic":"['frend.li]","pos":["adj"],"zh":"友善的","grade":3},
    {"word":"full","phonetic":"[fUl]","pos":["adj"],"zh":"飽的；滿的","grade":3},
    {"word":"future","phonetic":"['fju.tSR]","pos":["n"],"zh":"未來","grade":3},
    {"word":"garbage","phonetic":"['gar.bIdD]","pos":["n"],"zh":"垃圾","grade":3},
    {"word":"garden","phonetic":"['gar.dn]","pos":["n"],"zh":"花園","grade":3},
    {"word":"guess","phonetic":"[ges]","pos":["v", "n"],"zh":"猜；猜測","grade":3},
    {"word":"health","phonetic":"[helO]","pos":["n"],"zh":"健康","grade":3},
    {"word":"honest","phonetic":"['a.nIst]","pos":["adj"],"zh":"誠實的","grade":3},
    {"word":"interested","phonetic":"['In.trIs.tId]","pos":["adj"],"zh":"感興趣的","grade":3},
    {"word":"interesting","phonetic":"['In.trIs.tIG]","pos":["adj"],"zh":"有趣的","grade":3},
    {"word":"invite","phonetic":"[In'vAIt]","pos":["v"],"zh":"邀請","grade":3},
    {"word":"jacket","phonetic":"['dDZk.It]","pos":["n"],"zh":"夾克；外套","grade":3},
    {"word":"join","phonetic":"[dDcIn]","pos":["v"],"zh":"加入","grade":3},
    {"word":"leave","phonetic":"[liv]","pos":["v"],"zh":"離開；丟下","grade":3},
    {"word":"lesson","phonetic":"['lesn]","pos":["n"],"zh":"課；教訓","grade":3},
    {"word":"lose","phonetic":"[last]","pos":["v"],"zh":"輸；失去","grade":3},
    {"word":"loud","phonetic":"[lAUd]","pos":["adj"],"zh":"大聲的","grade":3},
    {"word":"map","phonetic":"[mZp]","pos":["n"],"zh":"地圖","grade":3},
    {"word":"married","phonetic":"['mer.id]","pos":["adj"],"zh":"已婚的","grade":3},
    {"word":"math","phonetic":"[mZO]","pos":["n"],"zh":"數學","grade":3},
    {"word":"maybe","phonetic":"['meI.bi]","pos":["adv"],"zh":"可能；也許","grade":3},
    {"word":"medicine","phonetic":"['med.I.sEn]","pos":["n"],"zh":"藥","grade":3},
    {"word":"moment","phonetic":"['moU.mEnt]","pos":["n"],"zh":"片刻","grade":3},
    {"word":"mountain","phonetic":"['mAUn.tn]","pos":["n"],"zh":"山","grade":3},
    {"word":"myself","phonetic":"[mAI'self]","pos":["pron"],"zh":"我自己","grade":3},
    {"word":"news","phonetic":"[nuz]","pos":["n"],"zh":"新聞","grade":3},
    {"word":"notice","phonetic":"['noU.tIs]","pos":["v", "n"],"zh":"注意到；通知；注意；通知","grade":3},
    {"word":"order","phonetic":"['cr.dR]","pos":["v", "n"],"zh":"點菜；訂購；定單","grade":3},
    {"word":"own","phonetic":"[oUn]","pos":["adj", "v"],"zh":"自己的；擁有","grade":3},
    {"word":"pay","phonetic":"[peI]","pos":["v"],"zh":"付錢","grade":3},
    {"word":"polite","phonetic":"[pE'lAIt]","pos":["adj"],"zh":"有禮貌的","grade":3},
    {"word":"present","phonetic":"[prI'zent]","pos":["v", "n"],"zh":"提出；禮物","grade":3},
    {"word":"pretty","phonetic":"['prIti]","pos":["adj", "adv"],"zh":"漂亮的；十分地","grade":3},
    {"word":"program","phonetic":"['proU.grZm]","pos":["n"],"zh":"節目","grade":3},
    {"word":"proud","phonetic":"[prAUd]","pos":["adj"],"zh":"感到光榮的；驕傲的","grade":3},
    {"word":"public","phonetic":"['pVb.lIk]","pos":["adj"],"zh":"公開的；公立的","grade":3},
    {"word":"quick","phonetic":"[kwIk]","pos":["adj"],"zh":"快的","grade":3},
    {"word":"quite","phonetic":"[kwAIt]","pos":["adv"],"zh":"完全地；相當","grade":3},
    {"word":"radio","phonetic":"['reI.di.oU]","pos":["n"],"zh":"收音機","grade":3},
    {"word":"rule","phonetic":"[rul]","pos":["v", "n"],"zh":"統治；裁決；規則","grade":3},
    {"word":"safe","phonetic":"[seIf]","pos":["adj"],"zh":"安全的","grade":3},
    {"word":"save","phonetic":"[seIv]","pos":["v"],"zh":"救；省；存錢","grade":3},
    {"word":"snack","phonetic":"[snZk]","pos":["n"],"zh":"點心","grade":3},
    {"word":"someone","phonetic":"['sVm.wVn]","pos":["pron"],"zh":"某人","grade":3},
    {"word":"sports","phonetic":"[spcrts]","pos":["adj"],"zh":"運動的","grade":3},
    {"word":"spring","phonetic":"[sprIG]","pos":["n"],"zh":"春天；泉","grade":3},
    {"word":"strange","phonetic":"[streIndD]","pos":["adj"],"zh":"奇怪的","grade":3},
    {"word":"taste","phonetic":"[teIst]","pos":["v"],"zh":"嚐","grade":3},
    {"word":"though","phonetic":"[ToU]","pos":["conj"],"zh":"雖然","grade":3},
    {"word":"ticket","phonetic":"['tIk.It]","pos":["n"],"zh":"票；罰單","grade":3},
    {"word":"tired","phonetic":"[tAIrd]","pos":["adj"],"zh":"疲倦的","grade":3},
    {"word":"traffic","phonetic":"['trZf.Ik]","pos":["n"],"zh":"交通","grade":3},
    {"word":"until","phonetic":"[Vn'tIl]","pos":["prep"],"zh":"直到","grade":3},
    {"word":"voice","phonetic":"[vcIs]","pos":["n"],"zh":"（人的）聲音","grade":3},
    {"word":"weak","phonetic":"[wik]","pos":["adj"],"zh":"虛弱的","grade":3},
    {"word":"whether","phonetic":"['weT.R]","pos":["conj"],"zh":"是否","grade":3},
    {"word":"wish","phonetic":"[wIS]","pos":["v"],"zh":"祝福","grade":3},
    {"word":"yourself","phonetic":"[jUr'self]","pos":["pron"],"zh":"你自己","grade":3},
    {"word":"airport","phonetic":"['er.pcrt]","pos":["n"],"zh":"飛機場","grade":4},
    {"word":"although","phonetic":"[al'ToU]","pos":["conj"],"zh":"雖然","grade":4},
    {"word":"America","phonetic":"[E'mer.I.kE]","pos":["n"],"zh":"美國；美洲","grade":4},
    {"word":"anyone","phonetic":"['en.i.wVn]","pos":["pron"],"zh":"任何人","grade":4},
    {"word":"apartment","phonetic":"[E'part.mEnt]","pos":["n"],"zh":"公寓","grade":4},
    {"word":"appear","phonetic":"[E'pIr]","pos":["v"],"zh":"出現","grade":4},
    {"word":"behind","phonetic":"[bI'hAInd]","pos":["prep"],"zh":"在……後面","grade":4},
    {"word":"bite","phonetic":"[bIt]","pos":["v"],"zh":"咬","grade":4},
    {"word":"boring","phonetic":"['bc.rIG]","pos":["adj"],"zh":"乏味的","grade":4},
    {"word":"borrow","phonetic":"['bar.oU]","pos":["v"],"zh":"借","grade":4},
    {"word":"bridge","phonetic":"[brIdD]","pos":["n"],"zh":"橋","grade":4},
    {"word":"carry","phonetic":"['keri]","pos":["v"],"zh":"提；搬運","grade":4},
    {"word":"club","phonetic":"[klVb]","pos":["n"],"zh":"俱樂部；夜總會；社團","grade":4},
    {"word":"copy","phonetic":"['kapI]","pos":["v", "n"],"zh":"拷貝；抄襲；拷貝；副本","grade":4},
    {"word":"corner","phonetic":"['kcr.nR]","pos":["n"],"zh":"角落","grade":4},
    {"word":"cost","phonetic":"[kast]","pos":["v", "n"],"zh":"花費；費用；成本","grade":4},
    {"word":"cross","phonetic":"[kras]","pos":["v", "n"],"zh":"越過；渡過；十字架","grade":4},
    {"word":"cut","phonetic":"[kVt]","pos":["v"],"zh":"切割；剪","grade":4},
    {"word":"dark","phonetic":"[dark]","pos":["adj"],"zh":"黑暗的","grade":4},
    {"word":"dead","phonetic":"[ded]","pos":["adj"],"zh":"死的","grade":4},
    {"word":"decorate","phonetic":"['dek.reIt]","pos":["v"],"zh":"佈置","grade":4},
    {"word":"department","phonetic":"[dI'part.mEnt]","pos":["n"],"zh":"部門","grade":4},
    {"word":"department store","phonetic":"[dI'part.mEnt stcr]","pos":["n"],"zh":"百貨公司","grade":4},
    {"word":"diary","phonetic":"['dAIEri]","pos":["n"],"zh":"日記","grade":4},
    {"word":"dirty","phonetic":"['d2.ti]","pos":["adj"],"zh":"骯髒的","grade":4},
    {"word":"dish","phonetic":"[dIS]","pos":["n"],"zh":"盤子；一盤菜","grade":4},
    {"word":"doll","phonetic":"[dal]","pos":["n"],"zh":"洋娃娃","grade":4},
    {"word":"dollar","phonetic":"['da.lR]","pos":["n"],"zh":"美元","grade":4},
    {"word":"drop","phonetic":"[drap]","pos":["v"],"zh":"（使）滴落；丟下","grade":4},
    {"word":"dry","phonetic":"[drAI]","pos":["adj"],"zh":"乾的","grade":4},
    {"word":"either","phonetic":"['i.TR]","pos":["adj", "adv", "conj"],"zh":"兩者之一；也；或者（和 or 連用）","grade":4},
    {"word":"elementary school","phonetic":"[el.I'men.tRi skul]","pos":["n"],"zh":"小學","grade":4},
    {"word":"else","phonetic":"[els]","pos":["adj"],"zh":"其他的","grade":4},
    {"word":"enter","phonetic":"['entR]","pos":["v"],"zh":"輸入；進入","grade":4},
    {"word":"expensive","phonetic":"[Ik'spen.sIv]","pos":["adj"],"zh":"貴的","grade":4},
    {"word":"factory","phonetic":"['fZk.tRi]","pos":["n"],"zh":"工廠","grade":4},
    {"word":"far","phonetic":"[far]","pos":["adj"],"zh":"遠的","grade":4},
    {"word":"fashionable","phonetic":"['fZSn.E.bL]","pos":["adj"],"zh":"時尚的","grade":4},
    {"word":"farmer","phonetic":"['far.mR]","pos":["n"],"zh":"農夫","grade":4},
    {"word":"festival","phonetic":"['fes.tE.vL]","pos":["n"],"zh":"節日","grade":4},
    {"word":"fill","phonetic":"[fIl]","pos":["v"],"zh":"充滿；填充","grade":4},
    {"word":"glad","phonetic":"[glZd]","pos":["adj"],"zh":"高興的","grade":4},
    {"word":"grade","phonetic":"[greId]","pos":["n"],"zh":"年級；分數","grade":4},
    {"word":"group","phonetic":"[grup]","pos":["n"],"zh":"一群","grade":4},
    {"word":"gym","phonetic":"[dDIm]","pos":["n"],"zh":"體育館；體育；體操","grade":4},
    {"word":"heat","phonetic":"[hit]","pos":["n"],"zh":"熱","grade":4},
    {"word":"herself","phonetic":"[h2'self]","pos":["pron"],"zh":"她自己","grade":4},
    {"word":"himself","phonetic":"[hIm'self]","pos":["pron"],"zh":"他自己","grade":4},
    {"word":"however","phonetic":"[hAU'ev.R]","pos":["adv"],"zh":"然而；不過","grade":4},
    {"word":"hurry","phonetic":"['h2.i]","pos":["v", "n"],"zh":"趕快；匆忙","grade":4},
    {"word":"interest","phonetic":"['In.trIst]","pos":["n"],"zh":"興趣","grade":4},
    {"word":"internet","phonetic":"['In.tR.net]","pos":["n"],"zh":"網際網路","grade":4},
    {"word":"interview","phonetic":"['In.tR.vju]","pos":["v", "n"],"zh":"面談；採訪","grade":4},
    {"word":"island","phonetic":"['AI.lEnd]","pos":["n"],"zh":"島嶼","grade":4},
    {"word":"joy","phonetic":"[dDcI]","pos":["n"],"zh":"歡喜；樂趣","grade":4},
    {"word":"knock","phonetic":"[nak]","pos":["v"],"zh":"敲","grade":4},
    {"word":"land","phonetic":"[lZnd]","pos":["v", "n"],"zh":"登陸；陸地","grade":4},
    {"word":"large","phonetic":"[lardD]","pos":["adj"],"zh":"大的","grade":4},
    {"word":"lazy","phonetic":"['leI.zi]","pos":["adj"],"zh":"懶惰的","grade":4},
    {"word":"leg","phonetic":"[leg]","pos":["n"],"zh":"腿","grade":4},
    {"word":"lend","phonetic":"[lend]","pos":["v"],"zh":"出借","grade":4},
    {"word":"less","phonetic":"[les]","pos":["adj"],"zh":"較少的","grade":4},
    {"word":"library","phonetic":"['lAI.brer.i]","pos":["n"],"zh":"圖書館","grade":4},
    {"word":"lid","phonetic":"[lId]","pos":["n"],"zh":"蓋子","grade":4},
    {"word":"lie","phonetic":"[lAI]","pos":["v", "n"],"zh":"說謊；躺；謊言","grade":4},
    {"word":"likely","phonetic":"['lAI.kli]","pos":["adj"],"zh":"有可能的","grade":4},
    {"word":"line","phonetic":"[lAIn]","pos":["v", "n"],"zh":"排隊；線；隊伍","grade":4},
    {"word":"list","phonetic":"[lIst]","pos":["v", "n"],"zh":"列成表；單子","grade":4},
    {"word":"machine","phonetic":"[mE'Sin]","pos":["n"],"zh":"機器","grade":4},
    {"word":"magic","phonetic":"['mZdD.Ik]","pos":["adj", "n"],"zh":"不可思議的；有魔力的；魔術","grade":4},
    {"word":"main","phonetic":"[meIn]","pos":["adj"],"zh":"最主要的","grade":4},
    {"word":"mark","phonetic":"[mark]","pos":["v", "n"],"zh":"做記號；記號","grade":4},
    {"word":"mind","phonetic":"[mAInd]","pos":["v", "n"],"zh":"介意；心智","grade":4},
    {"word":"mine","phonetic":"[mAIn]","pos":["pron"],"zh":"我的（東西）","grade":4},
    {"word":"modern","phonetic":"['ma.dRn]","pos":["adj"],"zh":"現代的","grade":4},
    {"word":"museum","phonetic":"[mju'zi.Em]","pos":["n"],"zh":"博物館","grade":4},
    {"word":"newspaper","phonetic":"['nuz.peIpR]","pos":["n"],"zh":"報紙","grade":4},
    {"word":"noise","phonetic":"[ncIz]","pos":["n"],"zh":"噪音","grade":4},
    {"word":"notebook","phonetic":"['noUt.bUk]","pos":["n"],"zh":"筆記本","grade":4},
    {"word":"nothing","phonetic":"['nVO.IG]","pos":["pron"],"zh":"無事；無物","grade":4},
    {"word":"officer","phonetic":"['a,fI.sR]","pos":["n"],"zh":"軍官；官員","grade":4},
    {"word":"once","phonetic":"[wVns]","pos":["adv"],"zh":"一次","grade":4},
    {"word":"pack","phonetic":"[pZk]","pos":["v", "n"],"zh":"包裝；一小包","grade":4},
    {"word":"package","phonetic":"['pZk.IdD]","pos":["n"],"zh":"包裹","grade":4},
    {"word":"pair","phonetic":"[per]","pos":["n"],"zh":"一副","grade":4},
    {"word":"pants","phonetic":"[pZnts]","pos":["n"],"zh":"褲子","grade":4},
    {"word":"pie","phonetic":"[pAI]","pos":["n"],"zh":"派（食品）","grade":4},
    {"word":"piece","phonetic":"[pis]","pos":["n"],"zh":"件；片","grade":4},
    {"word":"plane","phonetic":"[pleIn]","pos":["n"],"zh":"飛機","grade":4},
    {"word":"playground","phonetic":"['pleI.grAUnd]","pos":["n"],"zh":"遊樂場；運動場","grade":4},
    {"word":"police","phonetic":"[pE'lis]","pos":["n"],"zh":"警察","grade":4},
    {"word":"possible","phonetic":"['pa.sEbL]","pos":["adj"],"zh":"可能的","grade":4},
    {"word":"practice","phonetic":"['prAk.tIs]","pos":["v", "n"],"zh":"練習；訓練；練習","grade":4},
    {"word":"prepare","phonetic":"[prI'perd]","pos":["v"],"zh":"準備","grade":4},
    {"word":"repeat","phonetic":"[rI'pit]","pos":["v"],"zh":"重複","grade":4},
    {"word":"report","phonetic":"[rI'pcrt]","pos":["n", "v"],"zh":"報告；報道；報告；匯報","grade":4},
    {"word":"rise","phonetic":"[rAIz]","pos":["v"],"zh":"起身；升起","grade":4},
    {"word":"scared","phonetic":"[skerd]","pos":["adj"],"zh":"害怕的","grade":4},
    {"word":"season","phonetic":"['si.zn]","pos":["n"],"zh":"季節","grade":4},
    {"word":"seldom","phonetic":"['sel.dEm]","pos":["adv"],"zh":"很少地","grade":4},
    {"word":"shopkeeper","phonetic":"['Sapki.pR]","pos":["n"],"zh":"小店主","grade":4},
    {"word":"side","phonetic":"[sAId]","pos":["adj", "n"],"zh":"側面的；邊","grade":4},
    {"word":"simple","phonetic":"['sIm.pL]","pos":["adj"],"zh":"簡單的","grade":4},
    {"word":"smell","phonetic":"[sm3l]","pos":["v"],"zh":"聞","grade":4},
    {"word":"space","phonetic":"[speIs]","pos":["n"],"zh":"空位；太空","grade":4},
    {"word":"square","phonetic":"[skwer]","pos":["adj", "n"],"zh":"正方形的；正方形","grade":4},
    {"word":"successful","phonetic":"[sEk'ses.fl]","pos":["adj"],"zh":"成功的","grade":4},
    {"word":"system","phonetic":"['sIs.tEm]","pos":["n"],"zh":"系統","grade":4},
    {"word":"terrible","phonetic":"['ter.E.bL]","pos":["adj"],"zh":"可怕的","grade":4},
    {"word":"themselves","phonetic":"[TEm'selvz]","pos":["pron"],"zh":"他/她/它們自己","grade":4},
    {"word":"touch","phonetic":"[tVtS]","pos":["v"],"zh":"觸摸","grade":4},
    {"word":"trouble","phonetic":"['trVbL]","pos":["n"],"zh":"麻煩","grade":4},
    {"word":"twice","phonetic":"[twAIs]","pos":["adv"],"zh":"兩次","grade":4},
    {"word":"useful","phonetic":"['jus.fl]","pos":["adj"],"zh":"有用的","grade":4},
    {"word":"vendor","phonetic":"['ven.dR]","pos":["n"],"zh":"小販","grade":4},
    {"word":"video","phonetic":"['vId.i.oU]","pos":["n"],"zh":"錄影機；錄影帶","grade":4},
    {"word":"weight","phonetic":"[weIt]","pos":["n"],"zh":"重量","grade":4},
    {"word":"yet","phonetic":"[jet]","pos":["adv", "conj"],"zh":"尚未；但是；然而","grade":4},
    {"word":"above","phonetic":"[E'bVv]","pos":["prep"],"zh":"在……之上","grade":5},
    {"word":"abroad","phonetic":"[E'brad]","pos":["adv"],"zh":"在國外","grade":5},
    {"word":"accident","phonetic":"['Zk.sE.dnt]","pos":["n"],"zh":"事故；災禍","grade":5},
    {"word":"active","phonetic":"['Zk.tIv]","pos":["adj"],"zh":"活躍的","grade":5},
    {"word":"activity","phonetic":"[Zk'tIv.E.ti]","pos":["n"],"zh":"活動","grade":5},
    {"word":"actor","phonetic":"['Zk.tR]","pos":["n"],"zh":"男演員","grade":5},
    {"word":"actress","phonetic":"['Zk.trEs]","pos":["n"],"zh":"女演員","grade":5},
    {"word":"advice","phonetic":"[Ed'vAIs]","pos":["n"],"zh":"忠告","grade":5},
    {"word":"agree","phonetic":"[E'gri]","pos":["v"],"zh":"同意","grade":5},
    {"word":"bakery","phonetic":"['beI.kR.i]","pos":["n"],"zh":"麵包店","grade":5},
    {"word":"band","phonetic":"[bZnd]","pos":["n"],"zh":"樂團；樂隊","grade":5},
    {"word":"bank","phonetic":"[bZnk]","pos":["n"],"zh":"銀行；堤；岸","grade":5},
    {"word":"bear","phonetic":"[ber]","pos":["v", "n"],"zh":"承受；熊","grade":5},
    {"word":"beef","phonetic":"[bif]","pos":["n"],"zh":"牛肉","grade":5},
    {"word":"belong","phonetic":"[bI'laG]","pos":["v"],"zh":"屬於","grade":5},
    {"word":"belt","phonetic":"[belt]","pos":["n"],"zh":"腰帶","grade":5},
    {"word":"besides","phonetic":"[bI'sAIdz]","pos":["adv", "prep"],"zh":"並且；除……之外","grade":5},
    {"word":"blind","phonetic":"[blAInd]","pos":["adj"],"zh":"瞎的","grade":5},
    {"word":"blow","phonetic":"[bloU]","pos":["v"],"zh":"吹","grade":5},
    {"word":"boat","phonetic":"[boUt]","pos":["n"],"zh":"小船","grade":5},
    {"word":"bowl","phonetic":"[boUl]","pos":["n"],"zh":"碗","grade":5},
    {"word":"burn","phonetic":"[b2n]","pos":["v", "n"],"zh":"燒；燙傷；灼傷","grade":5},
    {"word":"businessman","phonetic":"['bIznIsmEn]","pos":["n"],"zh":"商人","grade":5},
    {"word":"cap","phonetic":"[kZp]","pos":["n"],"zh":"棒球帽；蓋子","grade":5},
    {"word":"cellphone","phonetic":"['selfoUn]","pos":["n"],"zh":"手機；大哥大","grade":5},
    {"word":"cheat","phonetic":"[tSit]","pos":["v"],"zh":"欺騙；作弊","grade":5},
    {"word":"circle","phonetic":"[","pos":["n"],"zh":"圓圈；集團","grade":5},
    {"word":"clerk","phonetic":"[kl2","pos":["n"],"zh":"店員；辦事員；職員","grade":5},
    {"word":"climb","phonetic":"[klAIm]","pos":["v"],"zh":"爬；攀登","grade":5},
    {"word":"cloudy","phonetic":"['klaUdI]","pos":["adj"],"zh":"多雲的；陰天的","grade":5},
    {"word":"comic","phonetic":"['kamIk]","pos":["adj", "n"],"zh":"滑稽的；漫畫","grade":5},
    {"word":"common","phonetic":"['kamEn]","pos":["adj"],"zh":"常見的","grade":5},
    {"word":"company","phonetic":"['kVmpEnI]","pos":["n"],"zh":"公司","grade":5},
    {"word":"control","phonetic":"[kEn'trol]","pos":["v"],"zh":"控制","grade":5},
    {"word":"conversation","phonetic":"[kanvE'seiSEn]","pos":["n"],"zh":"會話","grade":5},
    {"word":"correct","phonetic":"[kE'rekt]","pos":["adj", "v"],"zh":"正確的；改正；糾正","grade":5},
    {"word":"count","phonetic":"[kAunt]","pos":["v", "n"],"zh":"計算；數；計數；計算","grade":5},
    {"word":"cowboy","phonetic":"['kAUbci]","pos":["n"],"zh":"牛仔","grade":5},
    {"word":"cover","phonetic":"['kVvE]","pos":["v", "n"],"zh":"蓋住；封面","grade":5},
    {"word":"cream","phonetic":"[krim]","pos":["n"],"zh":"奶油","grade":5},
    {"word":"create","phonetic":"[kri'eit]","pos":["v"],"zh":"創造","grade":5},
    {"word":"deal","phonetic":"[dil]","pos":["v", "n"],"zh":"處理；對付；對待；交易","grade":5},
    {"word":"dessert","phonetic":"[dI'z2t]","pos":["n"],"zh":"餐後甜點","grade":5},
    {"word":"dictionary","phonetic":"['dikSEnEri]","pos":["n"],"zh":"字典","grade":5},
    {"word":"diet","phonetic":"['dAIEt]","pos":["v", "n"],"zh":"節食；飲食；特種飲食","grade":5},
    {"word":"dig","phonetic":"[dIg]","pos":["v"],"zh":"挖掘","grade":5},
    {"word":"earth","phonetic":"[2T]","pos":["n"],"zh":"地球；土地","grade":5},
    {"word":"east","phonetic":"[ist]","pos":["adj", "adv", "n"],"zh":"東方的；向東方；東方","grade":5},
    {"word":"envelope","phonetic":"['envE.lop]","pos":["n"],"zh":"信封","grade":5},
    {"word":"eraser","phonetic":"[I'resR]","pos":["n"],"zh":"橡皮擦","grade":5},
    {"word":"eve","phonetic":"[iv]","pos":["n"],"zh":"前夕","grade":5},
    {"word":"everybody","phonetic":"['3vrI.badI]","pos":["pron"],"zh":"每個人","grade":5},
    {"word":"everywhere","phonetic":"['3vrI.hw3r]","pos":["adv"],"zh":"到處","grade":5},
    {"word":"excellent","phonetic":"['3kslEnt]","pos":["adj"],"zh":"非常好的","grade":5},
    {"word":"except","phonetic":"[Ik's3pt]","pos":["prep"],"zh":"除……之外","grade":5},
    {"word":"feeling","phonetic":"['filIG]","pos":["n"],"zh":"感覺","grade":5},
    {"word":"fix","phonetic":"[fIks]","pos":["v"],"zh":"修理","grade":5},
    {"word":"fry","phonetic":"[frAI]","pos":["v", "n"],"zh":"油炸；炸薯條","grade":5},
    {"word":"glass","phonetic":"[glZs]","pos":["n"],"zh":"玻璃杯；玻璃","grade":5},
    {"word":"glove","phonetic":"[glVv]","pos":["n"],"zh":"手套","grade":5},
    {"word":"grass","phonetic":"[grZs]","pos":["n"],"zh":"草","grade":5},
    {"word":"ground","phonetic":"[grAUnd]","pos":["n"],"zh":"地面","grade":5},
    {"word":"habit","phonetic":"['hZbIt]","pos":["n"],"zh":"習慣","grade":5},
    {"word":"half","phonetic":"[hZf]","pos":["n"],"zh":"一半","grade":5},
    {"word":"hang","phonetic":"[hZG]","pos":["v"],"zh":"把……掛起；吊","grade":5},
    {"word":"headache","phonetic":"['h3d.ek]","pos":["n"],"zh":"頭痛","grade":5},
    {"word":"healthy","phonetic":"['h3lOI]","pos":["adj"],"zh":"健康的","grade":5},
    {"word":"helpful","phonetic":"['h3lpfEl]","pos":["adj"],"zh":"有益的","grade":5},
    {"word":"hide","phonetic":"[hAId]","pos":["v"],"zh":"躲；隱藏","grade":5},
    {"word":"hobby","phonetic":"['habI]","pos":["n"],"zh":"嗜好","grade":5},
    {"word":"hold","phonetic":"[hold]","pos":["v"],"zh":"拿著","grade":5},
    {"word":"itself","phonetic":"[It's3lf]","pos":["pron"],"zh":"它自己","grade":5},
    {"word":"joke","phonetic":"[dDok]","pos":["v", "n"],"zh":"開玩笑；笑話","grade":5},
    {"word":"knife","phonetic":"[nAIf]","pos":["n"],"zh":"刀子","grade":5},
    {"word":"knowledge","phonetic":"['nalIdD]","pos":["n"],"zh":"學問；知識","grade":5},
    {"word":"lake","phonetic":"[lek]","pos":["n"],"zh":"湖","grade":5},
    {"word":"lamp","phonetic":"[lZmp]","pos":["n"],"zh":"燈","grade":5},
    {"word":"least","phonetic":"[list]","pos":["n"],"zh":"最少","grade":5},
    {"word":"lip","phonetic":"[lIp]","pos":["n"],"zh":"嘴唇","grade":5},
    {"word":"lonely","phonetic":"['lonlI]","pos":["adj"],"zh":"寂寞的","grade":5},
    {"word":"low","phonetic":"[lo]","pos":["adj"],"zh":"低的；矮的","grade":5},
    {"word":"mailman","phonetic":"['mel.mZn]","pos":["n"],"zh":"郵差","grade":5},
    {"word":"marry","phonetic":"['mZrI]","pos":["v"],"zh":"結婚","grade":5},
    {"word":"meat","phonetic":"[mit]","pos":["n"],"zh":"肉類","grade":5},
    {"word":"medium","phonetic":"['midIEm]","pos":["adj"],"zh":"中等的","grade":5},
    {"word":"message","phonetic":"['m3sIdD]","pos":["n"],"zh":"消息；音信","grade":5},
    {"word":"million","phonetic":"['mIljEn]","pos":["n"],"zh":"百萬","grade":5},
    {"word":"national","phonetic":"['nZSEnl]","pos":["adj"],"zh":"國家的","grade":5},
    {"word":"nature","phonetic":"['netSR]","pos":["n"],"zh":"自然","grade":5},
    {"word":"neighbor","phonetic":"['nebR]","pos":["n"],"zh":"鄰居","grade":5},
    {"word":"noodle","phonetic":"['nudl]","pos":["n"],"zh":"麵","grade":5},
    {"word":"north","phonetic":"[ncrO]","pos":["adj", "adv", "n"],"zh":"北方的；向北方；北方","grade":5},
    {"word":"note","phonetic":"[noUt]","pos":["v", "n"],"zh":"注意；記下；筆記；音符；記錄；便條","grade":5},
    {"word":"novel","phonetic":"[navEl]","pos":["n"],"zh":"小說","grade":5},
    {"word":"oil","phonetic":"[cIl]","pos":["n"],"zh":"油","grade":5},
    {"word":"passenger","phonetic":"['pZsndDR]","pos":["n"],"zh":"乘客","grade":5},
    {"word":"perhaps","phonetic":"[pR'hZps]","pos":["adv"],"zh":"或許；可能","grade":5},
    {"word":"plant","phonetic":"[plZnt]","pos":["v", "n"],"zh":"栽種；播種；植物；農作物；工廠","grade":5},
    {"word":"plate","phonetic":"[plet]","pos":["n"],"zh":"盤；碟","grade":5},
    {"word":"pleasure","phonetic":"['pl3DR]","pos":["n"],"zh":"愉快","grade":5},
    {"word":"poem","phonetic":"['poIm]","pos":["n"],"zh":"詩","grade":5},
    {"word":"pocket","phonetic":"['pakIt]","pos":["n"],"zh":"口袋","grade":5},
    {"word":"point","phonetic":"[pcInt]","pos":["n"],"zh":"點；要點","grade":5},
    {"word":"pollution","phonetic":"[pE'luSen]","pos":["n"],"zh":"污染","grade":5},
    {"word":"post","phonetic":"","pos":[],"zh":"郵局","grade":5},
    {"word":"office","phonetic":"[post 'cfIs]","pos":["n"],"zh":"辦公室","grade":5},
    {"word":"pot","phonetic":"[pat]","pos":["n"],"zh":"罐；鍋","grade":5},
    {"word":"power","phonetic":"['pAUR]","pos":["n"],"zh":"權力；動力","grade":5},
    {"word":"prize","phonetic":"[prAIz]","pos":["n"],"zh":"獎品","grade":5},
    {"word":"produce","phonetic":"[prE'djus]","pos":["v", "n"],"zh":"製造；出產；農產品","grade":5},
    {"word":"rainbow","phonetic":"['ren.bo]","pos":["n"],"zh":"彩虹","grade":5},
    {"word":"refrigerator","phonetic":"[rI'frIdDE.retR]","pos":["n"],"zh":"電冰箱","grade":5},
    {"word":"review","phonetic":"[rI'vju]","pos":["v", "n"],"zh":"溫習；回顧；複習","grade":5},
    {"word":"sale","phonetic":"[sel]","pos":["n"],"zh":"售賣；賤賣","grade":5},
    {"word":"science","phonetic":"['sAIEns]","pos":["n"],"zh":"科學","grade":5},
    {"word":"seat","phonetic":"[sit]","pos":["n"],"zh":"座位","grade":5},
    {"word":"semester","phonetic":"[sE'm3stR]","pos":["n"],"zh":"學期","grade":5},
    {"word":"sentence","phonetic":"['s3ntEns]","pos":["v", "n"],"zh":"宣判；判決；句子","grade":5},
    {"word":"service","phonetic":"['s2vIs]","pos":["n"],"zh":"服務","grade":5},
    {"word":"shape","phonetic":"[Sep]","pos":["n"],"zh":"形狀","grade":5},
    {"word":"shine","phonetic":"[SAIn]","pos":["v"],"zh":"照耀","grade":5},
    {"word":"sidewalk","phonetic":"['sAId.wck]","pos":["n"],"zh":"路邊行人道","grade":5},
    {"word":"socks","phonetic":"[saks]","pos":["n"],"zh":"一雙襪子","grade":5},
    {"word":"solve","phonetic":"[salv]","pos":["v"],"zh":"解決","grade":5},
    {"word":"somewhere","phonetic":"['sVm.hw3r]","pos":["adv"],"zh":"在某處","grade":5},
    {"word":"soup","phonetic":"[sup]","pos":["n"],"zh":"湯","grade":5},
    {"word":"south","phonetic":"[sAUO]","pos":["adj", "adv", "n"],"zh":"南方的；向南方；南方","grade":5},
    {"word":"steak","phonetic":"[stek]","pos":["n"],"zh":"牛排","grade":5},
    {"word":"stomach","phonetic":"['stVmEk]","pos":["n"],"zh":"胃","grade":5},
    {"word":"stupid","phonetic":"['stupId]","pos":["adj"],"zh":"笨的","grade":5},
    {"word":"subject","phonetic":"['sVbdDIkt]","pos":["n"],"zh":"主題；學科","grade":5},
    {"word":"sugar","phonetic":"['SUgR]","pos":["n"],"zh":"糖","grade":5},
    {"word":"surprise","phonetic":"[sR'prAIz]","pos":["v", "n"],"zh":"使驚奇；意外之事物","grade":5},
    {"word":"sweater","phonetic":"['sw3tR]","pos":["n"],"zh":"毛衣","grade":5},
    {"word":"teenager","phonetic":"['tin.edDR]","pos":["n"],"zh":"十幾歲孩子","grade":5},
    {"word":"thirsty","phonetic":"['O2stI]","pos":["adj"],"zh":"口渴的","grade":5},
    {"word":"tip","phonetic":"[tIp]","pos":["v", "n"],"zh":"給小費；使傾斜；尖端；小費","grade":5},
    {"word":"title","phonetic":"['tAItL]","pos":["n"],"zh":"標題；頭銜","grade":5},
    {"word":"top","phonetic":"[tap]","pos":["adj", "n"],"zh":"最高的；頂部；陀螺","grade":5},
    {"word":"total","phonetic":"['totL]","pos":["adj", "n"],"zh":"總的；總額","grade":5},
    {"word":"towel","phonetic":"['tAUEl]","pos":["n"],"zh":"毛巾","grade":5},
    {"word":"treat","phonetic":"[trit]","pos":["v", "n"],"zh":"對待；治療；款待","grade":5},
    {"word":"unhappy","phonetic":"[Vn'hZpI]","pos":["adj"],"zh":"不快樂的","grade":5},
    {"word":"uniform","phonetic":"['junE.fcrm]","pos":["n"],"zh":"制服","grade":5},
    {"word":"village","phonetic":"['vIlIdD]","pos":["n"],"zh":"村落","grade":5},
    {"word":"wallet","phonetic":"['walIt]","pos":["n"],"zh":"皮夾","grade":5},
    {"word":"while","phonetic":"[hwAIl]","pos":["conj", "n"],"zh":"當……的時候；一會兒","grade":5},
    {"word":"whose","phonetic":"[huz]","pos":["pron"],"zh":"誰的","grade":5},
    {"word":"wise","phonetic":"[wAIz]","pos":["adj"],"zh":"有智慧的","grade":5},
    {"word":"workbook","phonetic":"['w2k.bUk]","pos":["n"],"zh":"作業簿","grade":5},
  ],
  phrases: [
    {"phrase":"about to","zh":"即將"},
    {"phrase":"according to","zh":"根據"},
    {"phrase":"a couple of","zh":"一對……；好幾個……"},
    {"phrase":"a few","zh":"一些"},
    {"phrase":"after all","zh":"畢竟"},
    {"phrase":"a great deal of +","zh":"很多；大量"},
    {"phrase":"a little","zh":"一點點"},
    {"phrase":"a lot","zh":"很多"},
    {"phrase":"a lot of = lots of","zh":"很多"},
    {"phrase":"a number of = many","zh":"很多……"},
    {"phrase":"along with","zh":"和……一起"},
    {"phrase":"all day long","zh":"一整天"},
    {"phrase":"all kinds of","zh":"各式各樣的"},
    {"phrase":"all night long","zh":"整夜"},
    {"phrase":"all of a sudden","zh":"突然間"},
    {"phrase":"all right","zh":"好"},
    {"phrase":"all the time = always","zh":"總是"},
    {"phrase":"amount to","zh":"總共……；總計……"},
    {"phrase":"argue with sb.","zh":"與人爭論"},
    {"phrase":"arrive in/at +","zh":"抵達……"},
    {"phrase":"ask for sth.","zh":"要求……東西"},
    {"phrase":"as a matter of fact","zh":"事實上"},
    {"phrase":"as for","zh":"至於……；關於……"},
    {"phrase":"as long as","zh":"只要"},
    {"phrase":"as soon as","zh":"一……就……"},
    {"phrase":"as to + N","zh":"關於……"},
    {"phrase":"as usual","zh":"一如往常"},
    {"phrase":"as well = too","zh":"也"},
    {"phrase":"as well as = and","zh":"和"},
    {"phrase":"at first","zh":"首先"},
    {"phrase":"at last","zh":"最後"},
    {"phrase":"at least","zh":"至少"},
    {"phrase":"at most","zh":"最多"},
    {"phrase":"at once = right away","zh":"立刻"},
    {"phrase":"at present","zh":"目前"},
    {"phrase":"at the age of","zh":"在……的年紀"},
    {"phrase":"at times = sometimes","zh":"有時候"},
    {"phrase":"at work","zh":"上班中"},
    {"phrase":"back up = support","zh":"支持"},
    {"phrase":"beV a piece of cake","zh":"很容易"},
    {"phrase":"beV able to","zh":"能夠"},
    {"phrase":"beV acquainted with","zh":"與某人熟識"},
    {"phrase":"beV afraid of + N","zh":"害怕……"},
    {"phrase":"beV angry with sb.","zh":"對某人生氣"},
    {"phrase":"beV ashamed of","zh":"引以為恥"},
    {"phrase":"beV based on","zh":"根據"},
    {"phrase":"beV bored with","zh":"對……感到無趣"},
    {"phrase":"beV busy + V-ing","zh":"忙於……"},
    {"phrase":"beV careful about","zh":"對……小心謹慎"},
    {"phrase":"beV concerned about","zh":"擔心"},
    {"phrase":"beV covered with","zh":"覆蓋"},
    {"phrase":"beV crazy about","zh":"瘋狂喜愛"},
    {"phrase":"beV curious about","zh":"對……感到好奇"},
    {"phrase":"beV different from","zh":"與……不同"},
    {"phrase":"beV dressed in","zh":"穿著"},
    {"phrase":"beV eager to + V","zh":"渴望做……"},
    {"phrase":"beV embarrassed about","zh":"感到尷尬的"},
    {"phrase":"beV familiar with","zh":"與……熟悉"},
    {"phrase":"beV famous for","zh":"以……著名"},
    {"phrase":"beV fond of = like = enjoy","zh":"喜歡"},
    {"phrase":"beV full of = beV filled with","zh":"充滿"},
    {"phrase":"beV good at","zh":"擅長於"},
    {"phrase":"beV good for","zh":"對……有益"},
    {"phrase":"beV harmful to","zh":"對……有害"},
    {"phrase":"beV in one's shoes","zh":"站在某人立場"},
    {"phrase":"beV interested in","zh":"對……感興趣"},
    {"phrase":"beV in danger","zh":"處於危險之中"},
    {"phrase":"beV known for = beV well-known for","zh":"以……著名"},
    {"phrase":"beV likely to","zh":"可能會……"},
    {"phrase":"beV made of","zh":"由……組成"},
    {"phrase":"beV married to","zh":"與……人結婚"},
    {"phrase":"beV proud of","zh":"為……感到驕傲"},
    {"phrase":"beV ready to","zh":"準備做某事"},
    {"phrase":"beV satisfied with","zh":"滿意……"},
    {"phrase":"beV sick of","zh":"感到厭惡"},
    {"phrase":"beV sure to","zh":"務必"},
    {"phrase":"beV thankful to sb. for sth.","zh":"因某事感激某人"},
    {"phrase":"beV tired of","zh":"感到厭煩"},
    {"phrase":"beV used to + V-ing","zh":"習慣於……"},
    {"phrase":"beV willing to","zh":"願意"},
    {"phrase":"beV worried about","zh":"擔心"},
    {"phrase":"beV worth + V-ing = beV worthy of","zh":"值得做……；值得"},
    {"phrase":"belong to sb.","zh":"屬於……人"},
    {"phrase":"believe in","zh":"相信"},
    {"phrase":"benefit from","zh":"受益"},
    {"phrase":"beV aware of","zh":"當心"},
    {"phrase":"break in","zh":"闖入"},
    {"phrase":"bring up sb.","zh":"扶養人長大"},
    {"phrase":"burst out + V-ing","zh":"突然開始"},
    {"phrase":"by accident = by chance","zh":"無意間……"},
    {"phrase":"by all means","zh":"務必；絕對"},
    {"phrase":"by means of","zh":"藉由；透過"},
    {"phrase":"by mistake","zh":"不小心地"},
    {"phrase":"by oneself","zh":"獨自；靠自己"},
    {"phrase":"by the way","zh":"順道一提"},
    {"phrase":"by way of","zh":"經由；經過"},
    {"phrase":"call it a day","zh":"結束當天的工作"},
    {"phrase":"call off","zh":"取消"},
    {"phrase":"call sb. down","zh":"責備某人"},
    {"phrase":"call up sb.","zh":"打電話給……"},
    {"phrase":"can't help + V-ing","zh":"忍不住"},
    {"phrase":"carry out","zh":"實行；達成"},
    {"phrase":"catch (a bad) cold","zh":"（重）感冒"},
    {"phrase":"catch fire","zh":"著火"},
    {"phrase":"catch one's eye","zh":"吸引某人注意"},
    {"phrase":"change one's mind","zh":"改變心意"},
    {"phrase":"cheat on sb.","zh":"對某人感情不忠"},
    {"phrase":"check in","zh":"飯店或班機登機手續"},
    {"phrase":"check out","zh":"飯店退房"},
    {"phrase":"cheer up","zh":"加油打氣"},
    {"phrase":"come back","zh":"回來；返回"},
    {"phrase":"come from","zh":"來自……"},
    {"phrase":"come true","zh":"夢想實現"},
    {"phrase":"come up with","zh":"想出……"},
    {"phrase":"compare A with B","zh":"將 A 和 B 做比較"},
    {"phrase":"complain about","zh":"抱怨"},
    {"phrase":"cool down","zh":"降溫；冷卻；平靜"},
    {"phrase":"count on","zh":"依賴；依靠"},
    {"phrase":"cover up","zh":"蓋住；掩蓋"},
    {"phrase":"day after day","zh":"日復一日"},
    {"phrase":"day off","zh":"放假"},
    {"phrase":"deal in…","zh":"交易買賣"},
    {"phrase":"deal with = handle","zh":"處理"},
    {"phrase":"depend on = count on","zh":"依賴；依靠"},
    {"phrase":"die from +","zh":"死於……"},
    {"phrase":"die of +","zh":"死於……"},
    {"phrase":"do one's best","zh":"盡全力"},
    {"phrase":"dozens of…","zh":"數打；數十個"},
    {"phrase":"dress up","zh":"盛裝打扮"},
    {"phrase":"drop off","zh":"降低"},
    {"phrase":"due to = thanks to = owing to = because of","zh":"由於……"},
    {"phrase":"each other","zh":"兩者中彼此"},
    {"phrase":"earn one's living","zh":"謀生"},
    {"phrase":"eat in","zh":"在家用餐"},
    {"phrase":"eat out","zh":"外食"},
    {"phrase":"end up + V-ing","zh":"結束"},
    {"phrase":"enjoy oneself","zh":"玩得開心"},
    {"phrase":"even if","zh":"雖然"},
    {"phrase":"every now and then","zh":"偶爾"},
    {"phrase":"every other day","zh":"每隔一天"},
    {"phrase":"fall apart","zh":"破碎裂；分解散開"},
    {"phrase":"fall asleep","zh":"睡著"},
    {"phrase":"fall behind","zh":"落後；跟不上"},
    {"phrase":"fall in love","zh":"與某人戀愛"},
    {"phrase":"feel like + V-ing","zh":"想要"},
    {"phrase":"feel sorry for","zh":"對……深感同情；遺憾"},
    {"phrase":"figure out","zh":"想出；解決"},
    {"phrase":"find out","zh":"發現"},
    {"phrase":"fool around","zh":"鬼混"},
    {"phrase":"for example = for instance","zh":"例如"},
    {"phrase":"for fear of","zh":"惟恐"},
    {"phrase":"for free","zh":"免費"},
    {"phrase":"for good = forever","zh":"永久"},
    {"phrase":"for sure","zh":"確定地"},
    {"phrase":"from a distance","zh":"從遠處"},
    {"phrase":"From now on","zh":"從現在開始"},
    {"phrase":"from then on","zh":"從那時起"},
    {"phrase":"get along with","zh":"與……相處融洽"},
    {"phrase":"generally speaking","zh":"一般來說"},
    {"phrase":"get in/on","zh":"上車"},
    {"phrase":"get in touch with","zh":"保持聯絡"},
    {"phrase":"get into trouble","zh":"惹麻煩"},
    {"phrase":"get lost","zh":"迷路"},
    {"phrase":"get off","zh":"下車"},
    {"phrase":"get on one's nerves","zh":"今人心煩"},
    {"phrase":"get out of","zh":"離開"},
    {"phrase":"get over","zh":"克服問題；疾病復原"},
    {"phrase":"get rid of","zh":"消除；去除"},
    {"phrase":"get to = arrive in/at","zh":"到達"},
    {"phrase":"get up","zh":"起床"},
    {"phrase":"get used to + V-ing","zh":"習慣；適應"},
    {"phrase":"give in","zh":"投降；讓步"},
    {"phrase":"give birth to","zh":"生孩子"},
    {"phrase":"give sb. a big hand","zh":"給予熱烈掌聲"},
    {"phrase":"give sb. a call","zh":"打電話給某人"},
    {"phrase":"give sb. a hand","zh":"幫助"},
    {"phrase":"give up +V-ing","zh":"放棄；戒除"},
    {"phrase":"go on","zh":"繼續"},
    {"phrase":"go on a diet","zh":"節食"},
    {"phrase":"go on a picnic","zh":"去野餐"},
    {"phrase":"go through","zh":"經歷……"},
    {"phrase":"go with","zh":"和……很搭配"},
    {"phrase":"grow into","zh":"漸漸成為或變得"},
    {"phrase":"grow up","zh":"成長"},
    {"phrase":"had better +","zh":"最好是"},
    {"phrase":"hand in = turn in","zh":"繳交"},
    {"phrase":"hang up","zh":"掛斷電話"},
    {"phrase":"have a gift for","zh":"在……有天賦"},
    {"phrase":"have a good time","zh":"玩得愉快"},
    {"phrase":"have a quarrel with","zh":"與某人吵架"},
    {"phrase":"have no idea (about","zh":"不知道"},
    {"phrase":"have to","zh":"必須"},
    {"phrase":"have something to do with","zh":"和……有關"},
    {"phrase":"happen to sb.","zh":"某事發生某人"},
    {"phrase":"hear of/about","zh":"聽說關於......"},
    {"phrase":"hear from","zh":"得到某人消息"},
    {"phrase":"help yourself to","zh":"自己拿……"},
    {"phrase":"hold on","zh":"稍等"},
    {"phrase":"how come = why","zh":"為什麼"},
    {"phrase":"hundreds of","zh":"數以百計"},
    {"phrase":"Hurry up","zh":"快一點"},
    {"phrase":"in a hurry","zh":"匆忙"},
    {"phrase":"in a word","zh":"簡言之"},
    {"phrase":"in addition (to)","zh":"除此之外"},
    {"phrase":"in advance","zh":"事先"},
    {"phrase":"in any case","zh":"無論如何"},
    {"phrase":"in case of","zh":"萬一……"},
    {"phrase":"in charge of","zh":"負責"},
    {"phrase":"in danger","zh":"處於危險中"},
    {"phrase":"in fact","zh":"事實上"},
    {"phrase":"in front of","zh":"在前面"},
    {"phrase":"in need of","zh":"需要"},
    {"phrase":"in order to = so as to","zh":"為了"},
    {"phrase":"in person","zh":"親自"},
    {"phrase":"in public","zh":"公開"},
    {"phrase":"in spite of = despite","zh":"盡管"},
    {"phrase":"in the end","zh":"最後……"},
    {"phrase":"in the past","zh":"在過去"},
    {"phrase":"in the future","zh":"在未來"},
    {"phrase":"instead of + N","zh":"而不是……"},
    {"phrase":"keep away from","zh":"遠離……"},
    {"phrase":"keep an eye on…","zh":"監視……"},
    {"phrase":"keep sb. from V-ing","zh":"使遠離"},
    {"phrase":"keep in order","zh":"將……保持整齊"},
    {"phrase":"keep in mind","zh":"記在心裡"},
    {"phrase":"keep in shape","zh":"保持身材"},
    {"phrase":"keep in touch with","zh":"保持聯絡"},
    {"phrase":"keep up with","zh":"跟上……"},
    {"phrase":"knock on the door","zh":"敲門"},
    {"phrase":"laugh at","zh":"嘲笑"},
    {"phrase":"less and less","zh":"越來越少"},
    {"phrase":"let sb. down","zh":"使某人失望"},
    {"phrase":"lie down","zh":"躺下"},
    {"phrase":"lie in","zh":"在於"},
    {"phrase":"line up","zh":"排隊"},
    {"phrase":"listen to = hear","zh":"聆聽"},
    {"phrase":"look after = take care of","zh":"照顧"},
    {"phrase":"look around","zh":"四處看"},
    {"phrase":"look at","zh":"注視"},
    {"phrase":"look down on/upon sb.","zh":"輕視某人"},
    {"phrase":"look for = search for","zh":"尋找"},
    {"phrase":"look forward to + V- ing","zh":"期待"},
    {"phrase":"look into","zh":"調查"},
    {"phrase":"look like","zh":"看起來像"},
    {"phrase":"look out = watch out","zh":"小心"},
    {"phrase":"look over sth.","zh":"檢查……東西"},
    {"phrase":"look up","zh":"查閱單字"},
    {"phrase":"lose one's head","zh":"失去理智"},
    {"phrase":"major in","zh":"主修"},
    {"phrase":"make a mistake","zh":"犯錯"},
    {"phrase":"make it a rule to","zh":"養成……習慣"},
    {"phrase":"make friends with","zh":"與某人做朋友"},
    {"phrase":"make fun of","zh":"取笑……"},
    {"phrase":"make sure","zh":"確定"},
    {"phrase":"make up","zh":"編造故事、藉口"},
    {"phrase":"make up for","zh":"彌補"},
    {"phrase":"make up one's mind to","zh":"下定決心"},
    {"phrase":"make use of","zh":"利用"},
    {"phrase":"melt away","zh":"融化；消失"},
    {"phrase":"mess up","zh":"弄亂；弄髒"},
    {"phrase":"mix up","zh":"混合"},
    {"phrase":"more and more","zh":"越來越多"},
    {"phrase":"more or less","zh":"或多或少……"},
    {"phrase":"name after","zh":"以……命名"},
    {"phrase":"never mind","zh":"別介意；沒關係"},
    {"phrase":"no doubt","zh":"無庸置疑"},
    {"phrase":"no longer","zh":"不再"},
    {"phrase":"not…at all","zh":"一點也不"},
    {"phrase":"of one's own","zh":"屬於自己的"},
    {"phrase":"on one's own","zh":"靠自己"},
    {"phrase":"on earth","zh":"世界上；究竟"},
    {"phrase":"on and off","zh":"斷斷續續"},
    {"phrase":"on business","zh":"出差"},
    {"phrase":"on foot","zh":"走路"},
    {"phrase":"on one's way to","zh":"到……的路上"},
    {"phrase":"on purpose","zh":"故意地"},
    {"phrase":"on one hand","zh":"一方面……"},
    {"phrase":"on the other hand","zh":"另一方面......"},
    {"phrase":"on time","zh":"準時"},
    {"phrase":"on vacation","zh":"度假"},
    {"phrase":"one another","zh":"彼此（三者以上）"},
    {"phrase":"out of date","zh":"落伍的"},
    {"phrase":"out of order","zh":"損壞；故障"},
    {"phrase":"out of the question","zh":"不可能的"},
    {"phrase":"out of work","zh":"失業"},
    {"phrase":"pass away","zh":"去世"},
    {"phrase":"pass by","zh":"經過；路過"},
    {"phrase":"pass out","zh":"暈倒"},
    {"phrase":"pay attention to","zh":"專心......"},
    {"phrase":"pick on sb.","zh":"找某人麻煩"},
    {"phrase":"pick out sth.","zh":"挑選出……"},
    {"phrase":"pick sb. up","zh":"接送某人"},
    {"phrase":"pick up sth.","zh":"拾/撿起……"},
    {"phrase":"play a joke on sb.","zh":"開某人玩笑"},
    {"phrase":"point at/to","zh":"指向......"},
    {"phrase":"point out","zh":"指出……"},
    {"phrase":"pray for","zh":"為……祈禱"},
    {"phrase":"prepare for","zh":"為......做準備"},
    {"phrase":"put away sth.","zh":"收拾整理……"},
    {"phrase":"put off = delay","zh":"延期……"},
    {"phrase":"put on","zh":"穿上衣物；增加......"},
    {"phrase":"put out","zh":"滅火"},
    {"phrase":"put up with = endure","zh":"忍受"},
    {"phrase":"rain cats and dogs","zh":"傾盆大雨"},
    {"phrase":"rely on = count on","zh":"依賴；依靠"},
    {"phrase":"result from","zh":"起因於"},
    {"phrase":"result in = cause","zh":"導致"},
    {"phrase":"right away","zh":"馬上；立刻"},
    {"phrase":"right now","zh":"目前；現在"},
    {"phrase":"run after = chase","zh":"追趕"},
    {"phrase":"run into = bump into","zh":"不期而遇"},
    {"phrase":"run out of","zh":"用完……"},
    {"phrase":"run the risk of","zh":"冒……的風險"},
    {"phrase":"run over","zh":"輾過……"},
    {"phrase":"scare away","zh":"嚇跑"},
    {"phrase":"search for = look for","zh":"尋找"},
    {"phrase":"set out for","zh":"出發前往"},
    {"phrase":"set up","zh":"設立；設置"},
    {"phrase":"shake hands","zh":"握手"},
    {"phrase":"show off","zh":"炫耀"},
    {"phrase":"show sb. around","zh":"帶某人四處遊覽"},
    {"phrase":"show up = appear","zh":"出現"},
    {"phrase":"shut up","zh":"閉嘴"},
    {"phrase":"sit down","zh":"坐下"},
    {"phrase":"so far","zh":"到目前為止"},
    {"phrase":"so adj./adv. that S + V","zh":"如此……以致於"},
    {"phrase":"sooner or later","zh":"遲早……"},
    {"phrase":"speed up","zh":"加速"},
    {"phrase":"stand by sb.","zh":"支持某人"},
    {"phrase":"stand for + N","zh":"代表……"},
    {"phrase":"stand up","zh":"站起來"},
    {"phrase":"stare at = look at","zh":"注視"},
    {"phrase":"stay away from","zh":"遠離"},
    {"phrase":"stay in touch with","zh":"與……保持聯絡"},
    {"phrase":"stay up = sit up","zh":"熬夜"},
    {"phrase":"stop by","zh":"順道經過"},
    {"phrase":"stop…from = prevent…from","zh":"防止某事發生"},
    {"phrase":"succeed in","zh":"成功地"},
    {"phrase":"suffer from +","zh":"飽受疾病"},
    {"phrase":"switch off = turn off","zh":"關掉電源"},
    {"phrase":"switch on = turn on","zh":"打開電源"},
    {"phrase":"take a seat","zh":"請就坐"},
    {"phrase":"take a nap","zh":"小睡一下"},
    {"phrase":"take a break/rest","zh":"休息一下"},
    {"phrase":"take a trip","zh":"旅行"},
    {"phrase":"take a walk","zh":"散步"},
    {"phrase":"take action to","zh":"付諸行動"},
    {"phrase":"take advantage of = use","zh":"利用"},
    {"phrase":"take care of = look after","zh":"照顧"},
    {"phrase":"take N for granted","zh":"視為理所當然"},
    {"phrase":"take N into consideration","zh":"把……列入考慮"},
    {"phrase":"take off","zh":"脫掉衣物；飛機起飛"},
    {"phrase":"take out","zh":"拿出"},
    {"phrase":"take over N","zh":"接管；接收"},
    {"phrase":"take part in = join","zh":"參加"},
    {"phrase":"take place = happen = occur","zh":"發生"},
    {"phrase":"take up","zh":"佔據空間、時間"},
    {"phrase":"teach sb. a lesson","zh":"給某人一個教訓"},
    {"phrase":"tear apart","zh":"撕開、撕碎某物"},
    {"phrase":"take turns + V-ing","zh":"輪流做……"},
    {"phrase":"tear down","zh":"拆掉；摧毀"},
    {"phrase":"thanks to = because of = due to = owing to","zh":"由於……"},
    {"phrase":"tend to V","zh":"易於……"},
    {"phrase":"the other day","zh":"前幾天"},
    {"phrase":"think about","zh":"考慮；想到"},
    {"phrase":"throw away/out","zh":"丟棄……"},
    {"phrase":"throw up","zh":"嘔吐"},
    {"phrase":"to one's surprise","zh":"令人驚訝……"},
    {"phrase":"too adj. to V","zh":"太……以致於不能"},
    {"phrase":"try on","zh":"試穿"},
    {"phrase":"turn around","zh":"轉身"},
    {"phrase":"turn down","zh":"轉小聲"},
    {"phrase":"turn down sb.","zh":"拒絕某人"},
    {"phrase":"turn in = hand in","zh":"繳交"},
    {"phrase":"turn into","zh":"轉變"},
    {"phrase":"turn off = switch off","zh":"關掉電器"},
    {"phrase":"turn on = switch on","zh":"打開電器"},
    {"phrase":"turn over","zh":"翻身；轉身；打翻"},
    {"phrase":"turn up","zh":"轉大聲"},
    {"phrase":"turn out to (be)","zh":"結果是……"},
    {"phrase":"up to date","zh":"最新的"},
    {"phrase":"used to + V","zh":"過去經常做……"},
    {"phrase":"wait for","zh":"等待"},
    {"phrase":"wake up","zh":"醒來"},
    {"phrase":"warm up","zh":"暖身"},
    {"phrase":"watch out for","zh":"小心……"},
    {"phrase":"wear out","zh":"用壞掉"},
    {"phrase":"work for","zh":"替某人工作"},
    {"phrase":"work out = figure out","zh":"解決"},
    {"phrase":"worry about","zh":"擔心"},
    {"phrase":"with ease = easily","zh":"輕鬆地"},
    {"phrase":"year after year","zh":"一年一年"},
    {"phrase":"You bet. = Of course","zh":"當然"},
  ],
};

if (typeof module !== 'undefined') module.exports = VOCAB_DATA;